export const GET_ERRORS = 'GET_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';

export const AUTH_LOADING = 'AUTH_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_ADD = 'USER_ADD';
export const USER_UPDATE = 'USER_UPDATE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERRORS = 'SIGNUP_ERRORS';

export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_ERRORS = 'OTP_ERRORS';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const TITLE_SUCCESS = 'TITLE_SUCCESS';

export const USERLIST_SUCCESS = 'USERLIST_SUCCESS'; 
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'; 
export const USER_VERIFICATION_SUCCESS = 'USER_VERIFICATION_SUCCESS'; 

export const COUNTRYLIST_SUCCESS = 'COUNTRYLIST_SUCCESS'; 
export const COUNTRYADD_SUCCESS = 'COUNTRYADD_SUCCESS'; 
export const COUNTRYADD_ERROR = 'COUNTRYADD_ERROR'; 
export const COUNTRYEDIT_SUCCESS = 'COUNTRYEDIT_SUCCESS'; 
export const COUNTRYACTIVEINACTIVE_SUCCESS = 'COUNTRYACTIVEINACTIVE_SUCCESS'; 

export const CLIENT_REQUEST_LIST_SUCCESS = 'CLIENT_REQUEST_LIST_SUCCESS'; 
export const CLIENT_REQUEST_LIST_ERROR = 'CLIENT_REQUEST_LIST_ERROR'; 


export const CLIENT_LIST_SUCCESS = 'CLIENT_LIST_SUCCESS'; 
export const CLIENT_LIST_ERROR = 'CLIENT_LIST_ERROR';

export const CLIENT_UPDATE_SUCCESS = 'CLIENT_UPDATE_SUCCESS'; 
export const CLIENT_UPDATE_ERROR = 'CLIENT_UPDATE_ERROR';

export const CLIENT_REGISTER_SUCCESS = 'CLIENT_REGISTER_SUCCESS'; 
export const CLIENT_REGISTER_ERROR = 'CLIENT_REGISTER_ERROR';

export const CLIENT_EDIT_SUCCESS = 'CLIENT_EDIT_SUCCESS'; 
export const CLIENT_EDIT_ERROR = 'CLIENT_EDIT_ERROR';

export const CLIENT_REGISTER_EMAIL_SUCCESS = 'CLIENT_REGISTER_EMAIL_SUCCESS'; 
export const CLIENT_REGISTER_EMAIL_ERROR = 'CLIENT_REGISTER_EMAIL_ERROR';

export const PSMT_REGISTER_SUCCESS = 'PSMT_REGISTER_SUCCESS'; 
export const PSMT_REGISTER_ERROR = 'PSMT_REGISTER_ERROR';


export const PSMT_OTP_SUCCESS = 'PSMT_OTP_SUCCESS'; 
export const PSMT_OTP_ERROR = 'PSMT_OTP_ERROR';

export const CLIENT_VERIFY_REQUEST_SUCCESS = 'CLIENT_VERIFY_REQUEST_SUCCESS'; 
export const CLIENT_VERIFY_REQUEST_ERROR = 'CLIENT_VERIFY_REQUEST_ERROR';

export const SERVICELIST_SUCCESS = 'SERVICELIST_SUCCESS'; 
export const SERVICEADD_SUCCESS = 'SERVICEADD_SUCCESS'; 
export const SERVICEADD_ERROR = 'SERVICEADD_ERROR'; 
export const SERVICEEDIT_SUCCESS = 'SERVICEEDIT_SUCCESS'; 
export const SERVICEACTIVEINACTIVE_SUCCESS = 'SERVICEACTIVEINACTIVE_SUCCESS'; 

